### PR TITLE
Allow to notify on custom channels

### PR DESCRIPTION
**Pull request by GerMalaz**
* Move the definition of the var slack_notification_channel from the Template to the Notification
* Apply the Notification (without a default channel) where the var slack_notification_channel is defined in the Host/Service.
     (it assumes such definition as an equivalent of slack_notifications == "enabled", using a custom channel)

### CODE REVIEW

**Comment by nisabek** [comment]
hey, thanks for contribution - wouldn't overriding slack_notification_channel in your Host/Service template achieve the same?..

**Comment by GerMalaz** [comment]
Welcome!

Did not try to redefine it in a Host/Service template (that would require a template for each channel, I think).

This way, the default template(s) can be used, and the channel definition can be delayed until the host/service definition.

**Comment by nisabek** [comment]
okay on a fresher look I think I get it now :)) And it won't break existing setups right? - sorry I just don't have a way to test it quickly. Looks like you apply the host and service specific templates on top of the existing ones - correct?

**Comment by GerMalaz** [comment]
Yes  on not breaking existing setups.

No templates on top of others (except for defining webhook and base_url).

The channel definition is deferred until the Nofification is applied, and is applied to those that define the channel to use.

**Comment by nisabek** [comment]
thanks!

**Comment by samchoraria** [comment]
Hi @GerMalaz @nisabek ,

I think this PR has introduced a breaking change, or at least (for me) makes use inconsistent with the [README.md](https://github.com/nisabek/icinga2-slack-notifications#readme).

With the codebase BEFORE the PR was merged, the following configuration worked as expected, using default channel unless overridden for host or service e.g. :-
```
template Notification "slack-notifications-user-configuration" {
    import "slack-notifications-default-configuration"

    vars.slack_notifications_webhook_url = "https://hooks.slack.com/services/ACC/T1/T2"
    vars.slack_notifications_icinga2_base_url = "https://myhost/icingaweb2"
    vars.slack_notifications_channel = "#zz_test_channel_1"
}

template Notification "slack-notifications-user-configuration-hosts" {
    import "slack-notifications-default-configuration-hosts"
    
    # override default slack channel
    vars.slack_notifications_channel = "#zz_test_channel_2"
}

template Notification "slack-notifications-user-configuration-services" {
    import "slack-notifications-default-configuration-services"
    
    # override default slack channel
    vars.slack_notifications_channel = "#zz_test_channel_3"
}
```
WITH the PR merged, default & override channels in `slack-notifications-user-configuration.conf` are **NOT** respected.

If the intention is to set defaults in `conf.d/templates.conf` for generic host / service definitions e.g. :-
```
template Host "generic-host" {
  ...
  vars.slack_notifications = "enabled"
  vars.slack_notifications_channel = "#zz_test_channel_2"
}
```
And/or to be able to override the channel in the `host` / `service` declaration e.g. :-
```
object Host "my-slack-test-host" {
  import "generic-host"
  ...
  # override slack channel
  vars.slack_notifications_channel = "#zz_test_channel_3"
  ...
}
```

For me, either / both the above changes raise critical re-declaration errors when validating with `icinga2 daemon -C`.

Could you please clarify how defaults & overrides should be implemented with this PR? 
I'm happy to continue using code as at commit 65bc0bfc3da66c2a724ea3a3ce74ebda837e9708 and may have just completely misunderstood @GerMalaz changes.

Tested on a HA Master/Master setup using Icinga 2.12.3 on RHEL/CentOS7:-
```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.3)
...
System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1062.el7.x86_64
  Architecture: x86_64
```

**Comment by GerMalaz** [comment]
My changes do assume slack_notifications == "enabled" use the default channel, 
and defining a channel means the notifications are enabled.

apply Notification "slack-notifications-notification-services" to Service {
      import "slack-notifications-user-configuration-services"      
      vars.slack_notifications_channel = "#monitoring_alerts"
      assign where service.vars.slack_notifications == "enabled"
}

if service.vars.slack_notifications == "enabled" is mixed with a custom channel, this is a bad assumption
Think this instead would work, paired with the other apply with just ignores service.vars.slack_notifications and assumed enabled if a channel is set [though maybe is should check for enabled, or maybe for not disabled].
Need to set a default channel if none is set as this change removed the default channel from the base definition.

apply Notification "slack-notifications-notification-services" to Service {
      import "slack-notifications-user-configuration-services"      
      vars.slack_notifications_channel = "#monitoring_alerts"
      assign where service.vars.slack_notifications == "enabled" and ! service.vars.slack_notifications_channel 
}

It does require a template for each channel to be used, though? This PR allows to define the channel at the host level.

My use cases for this:

        vars.mysql_slave[""] = {
                slack_notifications_channel = "#alerts-emer"
        }
        
          vars.passive["emer"] = {
                slack_notifications_channel = "#bbo-alerts-emer"
          }
          
Where passive is defined as (mysql_slave defined similarly but has default creds so not copying it):

apply Service "passive-no-freshness" for (passive => config in host.vars.passive) {
  import "satellite-service"
  import "endpoint-service"

  check_command = "passive"
  display_name = passive
  
  enable_active_checks = false
  max_check_attempts = 1

  vars += config

}

**Pull request merged**
